<!--
**DCGorilla62/DCGorilla62** is a ✨ _special_ ✨ repository because its `README.md` (this file) appears on your GitHub profile.

Here are some ideas to get you started:

- 🔭 I’m currently working on ...
- 🌱 I’m currently learning ...
- 👯 I’m looking to collaborate on ...
- 🤔 I’m looking for help with ...
- 💬 Ask me about ...
- 📫 How to reach me: ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...
-->

## Dennis H. Calderón

### PhD Candidate at The Ohio State University
- Experimental Astroparticle Physics
- Working on the High Energy Light Isotope eXperiment ([HELIX](http://helix.uchicago.edu/)) project. 
- [Personal Site](https://www.dhcalderon.com)
- [CV](https://www.dhcalderon.com/documents/Calderon_CV.pdf)
